### ISSUE TITLE
Fill "Today" section (UI).  

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#14]
<img width="417" alt="Screen Shot 2019-12-24 at 2 18 09 PM" src="https://user-images.githubusercontent.com/11796006/71387344-41bb6880-2658-11ea-9630-ea558bb64070.png">

##### **Main functionality of ‘Today’ screen (as per mock up):**
-	Today’s date displayed at the top and users are unable to modify it
-	Wear time and time out are displayed underneath and are calculated based on tracked time:
    - Tracking is happening manually through user selecting ‘Play’(for when aligners are in) or ‘Pause’ (for when aligners have been removed)
-	Aligner # is selected automatically, based on the treatment plan. (Would look into adding functionality to updated Aligner# through this screen at any time)
-	Number of days till the end of the treatment is calculated automatically, based on the data User provided in ‘My Treatment Section)

**Comment by RiLights** [comment]
@OlenkaP 
- Can you please explain why do we need "Today’s date" field? Is some functional or it just system date label?
- Does "You are wearing Aligner #" should be "You are wearing Aligner # days"?

**Comment by OlenkaP** [comment]
@RiLights Today's date field is just the system date label
You are wearing Aligner # should calculate which aligner user is wearing

i.e. If the start of the treatment is 1.12 and user wears each aligner for 7 days (these are welcome screen questions), on 28.12 they would see the message saying 'You're wearing Aligner #4 '

**Comment by RiLights** [comment]
Probably my question is not clear, sorry :)
Should we add “days” in to the end of “You're wearing Aligner #” sentence?

**Comment by OlenkaP** [comment]
oh yeah, that would be great idea :) @RiLights

**Comment by RiLights** [comment]
@OlenkaP Can you please review this screen (Pause animation is working):
![IMG_24C0913EE1B6-1](https://user-images.githubusercontent.com/11796006/71555285-661ba880-2a8f-11ea-94ad-b3e1a3d381bd.jpeg)

**Comment by OlenkaP** [comment]
@RiLights Looks awesome! 
Can you please remove “,” koma after Today? Should just say Today: 29 December 2019
Also should be Out time, rather than Our time. And maybe it’s possible to have it in the format hh:min (ie 02:34)?
In the bottom message please remove ‘of’. Can it please say “70 days left until you reach the end of your treatment”

Second to bottom message can say: 
“You have been wearing aligners for 3 days”

**Comment by RiLights** [comment]
@OlenkaP Thank you for your superfast feedback!

Can you please check if I did correction properly:
![IMG_0E8F190867F8-1](https://user-images.githubusercontent.com/11796006/71562136-9c831300-2ae3-11ea-9cca-d6b9e884e33d.jpeg)

**Comment by OlenkaP** [comment]
@RiLights Thank you! Love your work

Just the bottom line. Can it please say: “70 days left until you reach the end of your treatment”
I really love the screen

**Comment by RiLights** [comment]
@OlenkaP 
Unfortunately so long sentence can't be fit into one line :(
Suggestions:
- smaller letters.
- shorter sentence

**Comment by OlenkaP** [comment]
@RiLights Please try smaller letters. 
Otherwise if shorter sentence: “70 days left until the end of your treatment”

**Comment by RiLights** [comment]
What do you think about this size (would be nice to take a look at this screen from the phone)?
![IMG_206484042E41-1 2](https://user-images.githubusercontent.com/11796006/71563503-58990980-2af5-11ea-8421-f5294ef75eb5.jpeg)

**Comment by OlenkaP** [comment]
@RiLights Almost want for it to be a bit bigger, not sure whether possible though 
Also I feel like I wanna increase size of every element on the screen( just by a tiny bit)

**Comment by RiLights** [comment]
Increased in around 10-15 percent and is probably it is maximum for this text (without stick to the border lines)
![IMG_3E0A585539F8-1](https://user-images.githubusercontent.com/11796006/71566098-7f693700-2b19-11ea-8d13-572e61bfe6d8.jpeg)

**Comment by OlenkaP** [comment]
@RiLights looks good, thank you:)
