### ISSUE TITLE
Create welcome screens (collecting user data)

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#17]

**Comment by RiLights** [comment]
Profile button (User data list view) has reset "complete" state for debug purpose (if you need to go through welcome tour again).

**Comment by OlenkaP** [comment]
@RiLights on Welcome screens can we please add some of the improvements discussed before?
1. How many aligners do you require for your treatment? - Values should be limited from 1 to 200. Users should be able to change values manually (by hitting the field and typing in the number) as well as using '+' and '-' buttons
2. When did you start your treatment? - Calendar can go back up to 3 years from current date. (ie up to 27.12.2016)
3. Number of days for each aligner? - Range from 1 to 31. Users should be able to change values manually (by hitting the field and typing in the number) as well as using '+' and '-' buttons
4. Aligner number you’re wearing now? - Range from 1 to 200. Users should be able to change values manually (by hitting the field and typing in the number) as well as using '+' and '-' buttons
5. How many days have you been wearing current aligner for?  - Range from 1 to 31. Users should be able to change values manually (by hitting the field and typing in the number) as well as using '+' and '-' buttons

**Comment by RiLights** [comment]
@OlenkaP 
Ready to test in master branch.
