### ISSUE TITLE
Investigate data storage for a alignment track.

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#18]
@OlenkaP 
Can you please explain more detail about Calendar data, alignment track, how "Today" page should interact with Calendar and which type of date we should  store?

**Comment by OlenkaP** [comment]
@RiLights Ostap, please let me know if this information is sufficient or whether you would require more?

Today page, explained more in story #21, would flow information through to calendar page.
Calendar should be available from the ‘Start of the Treatment date’ and right up to the end of current month. No future calendar data needed.

![image](https://user-images.githubusercontent.com/52235757/71506801-43e72680-28e7-11ea-8787-227b73198589.png)

Wear time gets recorded against each date on the calendar. Recording happens through users using ‘Today’ screen and Pausing or Playing wear time, as explained before. Days, where wear time is <20 hours are highlighted in red .  
![image](https://user-images.githubusercontent.com/52235757/71506834-5eb99b00-28e7-11ea-9c66-3c5d1400d704.png)
   Today’s date is highlighted in blue. 	
![image](https://user-images.githubusercontent.com/52235757/71506847-68db9980-28e7-11ea-96fc-ff6218aa2b29.png)

All of the other days remain unhighlighted. 
Start of the week day is ‘Monday’. 
At the top of the calendar users are able to navigate to previous months if such months exist.
Users should be able to navigate to any of the past days in the calendar and see their:
-	Total wear time for that day
-	Total out time for that day
-	Periods of time when braces have been out
Calendar screen would look somewhat like this:
![image](https://user-images.githubusercontent.com/52235757/71507483-9295c000-28e9-11ea-9d15-8d1f47da89c9.png)

I believe, that we won't require a lot of data to be stored, and that all of it can be stored locally. Please use a storage method that you believe would be the most appropriate, as I'm not totally familiar with possible methods

_As the future enhancement I would like for users to be able to add ‘Wear Time’ and ‘Time off’ to certain date using calendar tab, but this is not MVP and shouldn’t be done in the first milestone._

**Comment by RiLights** [comment]
Hi @OlenkaP,

Clear. Probably main to option is to save data in to UserDefaults or separate .json file.
Need to try.

Meanwhile, you are described a lot of information for other tasks! 
That is really useful. Thank you!

**Comment by OlenkaP** [comment]
this have been completed and all of the information above has been added to wiki page
