### ISSUE TITLE
Info for "About AlignTime" page

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#22]

**Comment by RiLights** [comment]
@OlenkaP 
Can you please provide text for "About App". How you would like to see this view?
![IMG_2DD2EBF723CE-1](https://user-images.githubusercontent.com/11796006/71568126-9021a900-2b29-11ea-821a-dca0ebf000de.jpeg)

**Comment by OlenkaP** [comment]
AlignTime is a Mobile app, created by users to assist other users in keeping track of Invisalign braces wear time. AlignTime helps record your daily wear time for each tray, sends reminders if an aligner has been left out for too long and alerts you when its time to change your tray. You can monitor progress for each aligner wear time using Calendar functionality. 

@RiLights this is the initial information we should put on this page. Once we have more functionality I would update it accordingly too

**Comment by RiLights** [comment]
Looks nice!
Thank you. Updated "About App" page accordingly your text.
