### ISSUE TITLE
Implement functional "Today" tab.

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#24]
-	Today’s date displayed at the top and users are unable to modify it
-	Wear time and time out are displayed underneath and are calculated based on tracked time:
    - Tracking is happening manually through user selecting ‘Play’(for when aligners are in) or ‘Pause’ (for when aligners have been removed)
-	Aligner # is selected automatically, based on the treatment plan. (Would look into adding functionality to updated Aligner# through this screen at any time)
-	Number of days till the end of the treatment is calculated automatically, based on the data User provided in ‘My Treatment Section)

**Comment by RiLights** [comment]
@OlenkaP 
How we should count wear time if time is already in another day(after 24:00)?

**Comment by OlenkaP** [comment]
@RiLights i believe new count should start if time is 00-00 (midninght). this would make sense, woudn't it?

**Comment by RiLights** [comment]
Playground for Play/Pause button is here(works in background):
https://github.com/RiLights/aligntime/blob/185e31b18cafb4723ed6a3881238b5bbb0b2c08c/aligntime/Today/TodayManager.swift#L50-L62
![IMG_29B368A0B560-1](https://user-images.githubusercontent.com/11796006/71611607-24117480-2bff-11ea-808b-5d4681f81e73.jpeg)
"Out Time" works immediately after start application. @OlenkaP - is it correct behaviour?

**Comment by OlenkaP** [comment]
@RiLights hi sorry for the late reply. 
Do you mean immediately start the application for the first time? I would assume, that 'Wear Time' would start calculating immediately with an option for the users to use 'Pause' (this is purely based on the fact that users more often would wear their aligners than not).
And than I would expect application to remember the state that it has been left in before and counting time respectively

**Comment by RiLights** [comment]
Ok. Clear. Because now we have opposite behave.
