### ISSUE TITLE
Meetup

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#25]
@OlenkaP, @sergiy-nazarenko  If you don't mind would be nice make meetup somewhere at FaceTime or Hangouts to be more familiar who we are and what we are doing :)

How about Monday (December 30) morning for Poland and evening for New Zealand?

**Comment by OlenkaP** [comment]
@RiLights what time NZ time? Approximately? I just need to make sure I have internet connection at the place we are staying

**Comment by RiLights** [comment]
@sergiy-nazarenko @OlenkaP 
Probably it will related on Warsaw morning time. 
But any time will suit me.

FaceTime, Hangouts - which preferences do we have?

**Comment by sergiy-nazarenko** [comment]
Hej, I’m ready to meet :)

**Comment by RiLights** [comment]
@OlenkaP 
8:30 is Ok?

**Comment by OlenkaP** [comment]
@sergiy-nazarenko @RiLights im ready whenever you guys are too

**Comment by RiLights** [comment]
@OlenkaP @sergiy-nazarenko 

**Happy New Year Us!** And making a **best** apps. in this already current year!

![](https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2019/11/Apple-Apps-Event-2019-796x417.jpg)

**Comment by OlenkaP** [comment]
@RiLights @OlenkaP Happy New Year, guys! Hope we can achieve some impressive new goals in the 2020 :)
