### ISSUE TITLE
If application reopened (was closed and open) the "Today" tab count time from 0

### ISSUE THREAD

**Issue by sergiy-nazarenko** [RiLights/aligntime#30]
Is this bug or not? :)

**Comment by RiLights** [comment]
"today sheet" - what do you mean?

**Comment by sergiy-nazarenko** [comment]
I mean "Today" tab

**Comment by RiLights** [comment]
@sergiy-nazarenko 
Are you in the last comment from "master" branch? 
"Closed application" - do you mean removing app. from the memory or you are taking about background state?

**Comment by sergiy-nazarenko** [comment]
I will check...

**Comment by RiLights** [comment]
Before today it was just labels.
Now timer in Today tab works (of corse without registering) as it should be.
Removing app. from the memory is not handled (I'm not sure if it should be handled).

**Comment by sergiy-nazarenko** [comment]
But... when I remove app. from memory how it will send notification to me in this case?

**Comment by RiLights** [comment]
If you remove it from the memory then user even doesn't have a option to control start/pause. @OlenkaP  can you please clarify how curent your application is behaving in this case?

Anyway, I'm not sure we should worry about it right now.
Lets assuming that current our goal is updating in background. (https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh)

**Comment by OlenkaP** [comment]
@sergiy-nazarenko @RiLights i'm sorry i don't quite understand what is removing from the memory? just closing up from the background? i still get the notification on my phone, when app is closed (even on the background)

**Comment by OlenkaP** [comment]
if you mean removing it from my phone completely - don't think it would be a valid test scenario, as we don't expect users deleting app from their phone

**Comment by RiLights** [comment]
@OlenkaP 
What is going on when your force quit your app?
https://www.imore.com/how-force-quit-apps-iphone-ipad

**Comment by OlenkaP** [comment]
@RiLights Still get the notification

**Comment by RiLights** [comment]
Hmm... 
I don't know how to make it yet. 
But I believe we will figure out: )

**Comment by RiLights** [comment]
@OlenkaP 
Does timer works if force quit application (from you current one)?

**Comment by OlenkaP** [comment]
@RiLights yes, timer works if I force quit application

**Comment by RiLights** [comment]
@OlenkaP 
Thanks for clarification!
Looks like I already know how to solve it ツ

**Comment by OlenkaP** [comment]
@RiLights had no doubt in you :)
