### ISSUE TITLE
Wear and Off times for Calendar tab.

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#35]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/11796006/71778134-ac808280-300e-11ea-8c08-f533c1d7c645.png">

**Comment by RiLights** [comment]
@OlenkaP 
Would be nice to understand from which menu (UI) you see changing those values (Wear/Off intervals)

**Comment by OlenkaP** [comment]
@RiLights can you please share a screen shot of how calendar tab currently looks with me? 
i then hopefully would have better idea (wanna have wear and off times on the calendar tab, just not sure where etc)

**Comment by RiLights** [comment]
Calendar is not ready yet.
I will try to implement Wear/Off intervals separately (but on the same screen).

**Comment by RiLights** [comment]
Hi @OlenkaP,

Can you please review Time Interval edit workflow:
![IMG_0838](https://user-images.githubusercontent.com/11796006/71884004-5fcab200-319c-11ea-824f-1bffd99997b0.PNG)
->-----------
![IMG_0836](https://user-images.githubusercontent.com/11796006/71884013-63f6cf80-319c-11ea-9bed-0526884a5ac9.PNG)
->-----------
![IMG_0835](https://user-images.githubusercontent.com/11796006/71884048-707b2800-319c-11ea-8233-9ac6ab32d2ac.PNG)

Do we need to change/delete current interval values?
From the "plus" on your screen mockup is not really clear how you would like to change/delete current interval values.

**Comment by OlenkaP** [comment]
@RiLights thank you for doing this, it looks very good.

Very good question. First part is easy explanation (not sure whether implementation would be that easy):

When user changes Wear time 00-00 - 7-30 to let say 00-00 - 06-00 - current "Wear Time' values should just get updated to a new values. 'Off Times' should get updated respectively too ( in this instance 'Off Time' would be updated to 06-00 - 7-30, as we assume, users had their aligner our from 06-00 till 7-30) 


When user changes Off Time (more likely scenario too) from 07-00 - 7-30 to 6-45 - 7-15 wear times would get updated accordingly to 00-00 - 06-45 and 07-15 - 12-00

Second part is tricky as we want users to be able to add wear time/off time using 'Add Wear Time' or 'Add Off Time' functionality 

![image](https://user-images.githubusercontent.com/52235757/71928184-e4005200-31fb-11ea-8309-14a4482c3532.png)

When user adds the time manually we need to make sure, that the timeslot they select sort of 'slides in' the other time slots, rather then simply adds on top. In my current app it simply adds on top and therefore i end up with 36 hours days etc.

The idea is when user adds 'Off Time' i.e. from 10-00 till 10-15 it adds it to the off time side of the screen and wear times would also get updated

![image](https://user-images.githubusercontent.com/52235757/71928768-0f377100-31fd-11ea-8065-5f674614b541.png)

I also expect Users to be able to add 'Off Time' only if timer is currently in 'Play' mode and 'Pause is displayed on Today's Tab as there would be no point in them adding Off Time if Off Time currently gets calculated 

A lot of words but hopefully it makes a bit of sense?

**Comment by RiLights** [comment]
Here some playing with UI (To make it more simpler):
![IMG_0839](https://user-images.githubusercontent.com/11796006/71955361-f22a8e80-324c-11ea-9da3-6904bdb1a90e.PNG)
Now it without additional window. You have just "Add" button in the right top corner.
>-----
![IMG_0841](https://user-images.githubusercontent.com/11796006/71955394-08d0e580-324d-11ea-9f0c-c67ac0b1df6c.PNG)
You are able to delete field by the left swipe.
>-----
![IMG_A6A57FB8E99C-1](https://user-images.githubusercontent.com/11796006/71955421-2605b400-324d-11ea-943b-59af29f3ed64.jpeg)
Probably, instead of keyboard (to change a values) it should number pad

**Comment by OlenkaP** [comment]
@RiLights it looks very nice this way! love that you got rid of one extra screen :)

will be interesting to see how it looks like with the number pad, otherwise, I'm quite happy with the keyboard (is it a numeric keyboard, or does the user have to change from alphabetic to numeric?)

**Comment by RiLights** [comment]
Thank you for review!

But unfortunately in this implementation user have to change to numeric keyboard (like in welcome screen). 
Probably will be better to change it to roller picker:
![image](https://user-images.githubusercontent.com/11796006/71961157-a92e0680-325b-11ea-828f-c99423c1797c.png)

But now I will leave it as it is.
Focusing more on data structure.

**Comment by RiLights** [comment]
Another possible state is when you are continuing in another day:
![IMG_D4DEB288CB48-1](https://user-images.githubusercontent.com/11796006/71963049-ab925f80-325f-11ea-941a-560fbb9da1d8.jpeg)

**Comment by OlenkaP** [comment]
would it make it even more complicated?

**Comment by RiLights** [comment]
Probably it will increase the complexity of the application but do we have another choice to visualize(managing) days interfering? 
How it is implemented in your current app.?

**Comment by OlenkaP** [comment]
so this is how my current one looks like 
it does tracking from the previous days, but it doesn't really track out time, just wear time and i think it would be nice for users to see out time straight away too.


![11](https://user-images.githubusercontent.com/52235757/72027970-cb6c6680-32e5-11ea-815c-8314ba55a752.png)
![22](https://user-images.githubusercontent.com/52235757/72027971-cb6c6680-32e5-11ea-8508-cde03124992c.png)

**Comment by RiLights** [comment]
So it showing previous/next day time in a grey colour.
Does selfie is a useful function?

**Comment by OlenkaP** [comment]
not really, cause it's hard to see progress based on selfies to be honest.
i have used it on weeks 1,2 and then week 17 and could see no difference , so gave up on using it

**Comment by RiLights** [comment]
@OlenkaP 
I'm wondering what the UI you have to change a time values?

**Comment by RiLights** [comment]
Actually I decided to make a proper UI for time picker.
![IMG_065373ADB248-1](https://user-images.githubusercontent.com/11796006/72055191-3c843c00-332f-11ea-9ddc-36eec68e8e45.jpeg)
Problem is that I can't add label to time picker (like next day) because it is all integer.
Maybe somebody has some ideas how to set previous/next day (continues time)?
Maybe some conceptual new idea?

**Comment by RiLights** [comment]
Maybe just to add Date picker?
![IMG_5E88BF5F985E-1](https://user-images.githubusercontent.com/11796006/72056691-f086c680-3331-11ea-9980-f598d657d34e.jpeg)

**Comment by RiLights** [comment]
Or maybe something like that:
![IMG_F9AE9E507A97-1](https://user-images.githubusercontent.com/11796006/72063100-00a4a300-333e-11ea-9fac-acf15d2732a7.jpeg)

**Comment by OlenkaP** [comment]
![IMG_4158 3189](https://user-images.githubusercontent.com/52235757/72124822-fed4f100-33ca-11ea-8652-ffb3c2364994.PNG)
They have a date picker like this currently (i have remembered that it glitches too under certain conditions and would let you select time so you have to re-select)

**Comment by RiLights** [comment]
Thanks!
In our case it is just time (without day) lets see if that make sense.
Anyway, last commit has working prototype ready to test.

**Comment by RiLights** [comment]
Hmm... maybe we can create a slider to represent (modify) time intervals?
![ranger-slider-gabrielsmelo](https://user-images.githubusercontent.com/11796006/72203189-aaff0080-34cd-11ea-9469-802aa074a68c.jpg)

**Comment by RiLights** [comment]
While playing with time range I'm wondering what we should do in this case:While playing with time range I'm wondering what we should do in this case:
![IMG_0CAD42ED1A58-1](https://user-images.githubusercontent.com/11796006/72215209-fe785980-3574-11ea-9bfc-67b9b1e53d45.jpeg)
What we should do when start and end range is equal?

**Comment by OlenkaP** [comment]
just don't calculate anything towards wear time/off time i would say 
technically this is 0 minutes

**Comment by RiLights** [comment]
What do you think about '....' (points) instead of time from previous day?
Maybe better to leave approach from your current app. (show dates from previous/next day)?
Are you able to modify time from previous/next day?

**Comment by OlenkaP** [comment]
yeah happy to leave dates/times from the previous days like it is in the current app 
(functionality works too)

**Comment by RiLights** [comment]
Ok. Thanks.
Continue testing functionality.

**Comment by RiLights** [comment]
Hey @OlenkaP, 

What system should do if one of the interval is deleted by user?

**Comment by OlenkaP** [comment]
@RiLights if the interval is deleted by a user i would expect bordering intervals to be updated with those values
if wear time interval was deleted, then it should automatically be added to 'off time values' and if 'off time' interval has been deleted, this should be automatically added to 'wear time'

**Comment by RiLights** [comment]
Do you mean merge with the previous interval?

**Comment by OlenkaP** [comment]
Yes

**Comment by RiLights** [comment]
Thanks for the clarification!

@sergiy-nazarenko

**Comment by RiLights** [comment]
Hey @OlenkaP 

And example question about state date, lets imagine we have:
07:00 - wear
08:00 - off
09:00 - wear
10:00 - off

then if we are deleting 08:00 then we have 2 wear states close to each other. How to solve that?

**Comment by OlenkaP** [comment]
@RiLights i would imagine that those should be merged together

i don't think there can any be 2 wear times in a row, without off time between
