### ISSUE TITLE
Create Logo/Icon to represent a project

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#6]

**Comment by OlenkaP** [comment]
![icon](https://user-images.githubusercontent.com/52235757/69700015-491d4e00-114e-11ea-9f89-aa03d4dbf487.png)

**Comment by RiLights** [comment]
Really fast tickets solving : )

**Comment by RiLights** [comment]
Can you tell me please, how do you see this logo design in the UI interface (possible including light/dark theme)? 

A couple of Apple design guidelines links:
https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/
https://developer.apple.com/design/resources/

**Comment by OlenkaP** [comment]
I have read a lot about icon making in the past few days and have decided, that something like this would be way more appropriate to be the icon for 'AlignTime" (for now, anyway)
![AlignTime icon](https://user-images.githubusercontent.com/52235757/70121671-f0acfa00-16d3-11ea-8b2b-055576fcad99.png)

**Comment by OlenkaP** [comment]
as for the color scheme, I quite like Accessible 'System Blue' theme, which consists of dark blue and light blue.
i expect some of the other main colours to be present (black, white, red) and i think that would be it.
thank you very much for sharing those articles with me - have learned heaps and literally had no idea and never paid any attention to the icons, but not any longer :)
<img width="554" alt="theme" src="https://user-images.githubusercontent.com/52235757/70121964-8fd1f180-16d4-11ea-9c96-b5e45a19d54a.PNG">

**Comment by RiLights** [comment]
> I have read a lot about icon making in the past few days and have decided, that something like this would be way more appropriate to be the icon for 'AlignTime" (for now, anyway)
> ![AlignTime icon](https://user-images.githubusercontent.com/52235757/70121671-f0acfa00-16d3-11ea-8b2b-055576fcad99.png)

Agree! I hope it was an interesting journey : )
