### ISSUE TITLE
Go through wireframes to check, whether they make sense

### ISSUE THREAD

**Issue by OlenkaP** [RiLights/aligntime#8]
https://www.figma.com/file/QqnBMB5gBNUjQwmjfljTMr/Welcome-Page?node-id=0%3A1

Ostap, please have a look at this and tell me whether this all make sense and would give you general idea, where to start.

You can use "Play" button to see actual prototype. You are also able to click on most of the buttons to see what they are doing.

There is also comments section, where I have added some of my explanations as to what this functionality is meant to do.

**Comment by RiLights** [comment]
@OlenkaP Correct me please if I'm wrong but the application will have two main windows: Data Init (Welcome) - for the first setup (and never show again). Main navigation window - User workflow?

**Comment by OlenkaP** [comment]
@RiLights no, you are totally right. Two main windows as per your comment above

**Comment by RiLights** [comment]
@OlenkaP 
Some questions:
 - What the responsibility of "Cancel" button? Maybe it should be "Back"?
 - Why "Cancel" and "Next" are different color? Are they in different state (Visualised in your mockup)?
 - What do you think to swap "Cancel" and "Next" position? Right: means forward, Left: cancel (back)
 - Maybe on the last page "Next" button should be replaced on "Finish", "Done", ...?
