### ISSUE TITLE
Basic Calendar Tab (UI)

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#9]
Implementing the basic calendar tab.

Simple scatch of calendar window (the way how it should look like)
<img width="326" alt="Screen Shot 2019-12-23 at 11 21 32 PM" src="https://user-images.githubusercontent.com/11796006/71353060-d1bbcc80-25dc-11ea-8ccc-545ee437c5a4.png">

General scatch:
<img width="908" alt="Screen Shot 2019-12-23 at 11 48 54 PM" src="https://user-images.githubusercontent.com/11796006/71353731-d2556280-25de-11ea-857c-0bb7cf3f3182.png">

Here is the supposed structure for the Calendar implementation. Please, feel free to change/organize architecture to your taste and view :) 
https://github.com/RiLights/aligntime/blob/830042531914a4384fff933433e6969cf962963c/aligntime/Calendar/Calendar.swift#L11-L23

**Comment by sergiy-nazarenko** [comment]
This can be implemented :)
https://iosexample.com/swiftui-simple-calendar-date-picker-for-ios/

**Comment by RiLights** [comment]
👍

**Comment by RiLights** [comment]
@sergiy-nazarenko Can you please add screens of "Calendar" tab?
Would be nice if @OlenkaP can review it.

**Comment by sergiy-nazarenko** [comment]
Here we go
![E5E06D65-B712-4C0B-B067-B68E03B987DD](https://user-images.githubusercontent.com/15361425/71510527-88df6e80-288f-11ea-9733-2881402d29ee.png)

**Comment by sergiy-nazarenko** [comment]
That is a dark theme preview because I have turned on it. Calendar is scrollable :)

**Comment by OlenkaP** [comment]
@sergiy-nazarenko looks really cool!
a few questions:
do you think it would be possible to have just monthly view with the ability of change between months?
is it possible for todays date to be highlighted in blue? not sure even whether it would look good, but would be nice to try?
please refer to story #23 for more detailed info :) 

@RiLights FYI

**Comment by RiLights** [comment]
Hey @sergiy-nazarenko 
Checking your last master commits I found that it provides a couple of warning messages:
```
ForEach<Range<Int>, Int, RKMonth> count (12) != its initial count (1).  
`ForEach(_:content:)` should only be used for *constant* data. 
Instead conform data to `Identifiable` or use `ForEach(_:id:content:)` and provide an explicit `id`!
AlignTime[10381:3246710] [TableView] 
Warning once only: 
UITableView was told to layout its visible cells and other contents without being in the view hierarchy 
(the table view or one of its superviews has not been added to a window). 
This may cause bugs by forcing views inside the table view to load and perform layout without accurate information 
(e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. 
Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy 
to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, 
or defer it until the table view has been added to a window. 
Table view: <_TtC7SwiftUIP33_BFB370BA5F1BADDC9D83021565761A4925UpdateCoalescingTableView: 0x10500dc00; 
baseClass = UITableView; frame = (0 0; 375 597.667); 
clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x282d4a070>;
layer = <CALayer: 0x2823bf3a0>; contentOffset: {0, 0}; 
contentSize: {375, 2987.3333333333335}; adjustedContentInset: {0, 0, 83, 0}; 
dataSource: <_TtGC7SwiftUIP10$1d8d9917419ListCoreCoordinatorGVS_20SystemListDataSourceOs5Never_GOS_19SelectionManagerBoxS2___: 0x104a0bc50>>
```
And looks like it provides poor UI performance. Maybe we should show only one month (as Olenka mentioned)?

**Comment by RiLights** [comment]
Probably, will be nice if press on month and it will expand to whole page (with all months)

**Comment by RiLights** [comment]
Like you had before

**Comment by sergiy-nazarenko** [comment]
You mean get rid of buttons and use scroll up/down option?

**Comment by RiLights** [comment]
Do not need to make any rid of :)
Just possibility of expanding calendar to all months (Like you had in the beginning)

**Comment by RiLights** [comment]
![](https://user-images.githubusercontent.com/15361425/71510527-88df6e80-288f-11ea-9733-2881402d29ee.png)

**Comment by OlenkaP** [comment]
i can really make up of what it looks now, but sounds like a great idea to be able to extend calendar to all month with the default view still remaining as current month

**Comment by sergiy-nazarenko** [comment]
> Do not need to make any rid of :)
> Just possibility of expanding calendar to all months (Like you had in the beginning)

Could you give me an example how looks like would be both option together?
